### ISSUE TITLE
Decawave release date for Mynewt 

### ISSUE THREAD

**Issue by enessuren** [Decawave/mynewt-dw1000-core#6]
Hi everyone,

Im using DWM1001-DEV with MyNewt OS. Some sample codes don’t work but some are working. When I looked at the decawave core bsp codes I thought it was not complete. am i right ? if im right, do u know a release date for core codes ?

Best Regards
Enes

**Comment by pkettle** [comment]
Hi Enes,

The mynewt-dw1000-core and associated mynewt-dw1000-apps examples should be working out-of-the-box. We have recently completed a refactoring of this code and are in the final throw of verification. We will tag these release shortly. Is there a particular example that you are referencing?

**Comment by enessuren** [comment]
Hi pkettle
for example, lwip_ping_rx and lwip_ping_tx build clearly. but i cant build twr_node_tdma, twr_tag_tdma (and other examples start with twr_...). i always get same error. like this;

Error: repos/mynewt-dw1000-core/lib/twr_ds_ext/src/twr_ds_ext.c:105:5: error: initializer element is not constant                               .tx_holdoff_delay = MYNEWT_VAL(TWR_DS_EXT_TX_HOLDOFF),         // Send Time delay in usec.                                                 ^                                                                                                                                     repos/mynewt-dw1000-core/lib/twr_ds_ext/src/twr_ds_ext.c:105:5: error: (near initialization for 'g_config.tx_holdoff_delay')               repos/mynewt-dw1000-core/lib/twr_ds_ext/src/twr_ds_ext.c:107:1: error: initializer element is not constant                                  };                                                                                                                                         ^                                                                                                                                         repos/mynewt-dw1000-core/lib/twr_ds_ext/src/twr_ds_ext.c:107:1: error: (near initialization for 'g_config.rx_timeout_period')
--

i checked all this makros (MYNEWT_VAL (x)) defined in syscfg.h file. path is this, \bin\targets\twr_node_tdma\generated\include\syscfg\. but i dont know, why my compiler doesnt see them. any idea, why i get this error all times ?

note: i never changed a code and i checked every stage over and over again. btw sorry about my bad english :)

**Comment by pkettle** [comment]
Hi Enes, 

Interesting, what compiler version are you using? 

Could I have you edit the following and report back:
mynewt-dw1000-apps/repo/mynewt-dw1000-core/lib/twr_ds_ext/syscfg.yml to: 

```
  TWR_DS_EXT_TX_HOLDOFF:
        description: 'tx holdoff delay for DS TWR extended frame (usec)'
        value: ((const uint32_t){0x0360})
      TWR_DS_EXT_RX_TIMEOUT:
        description: 'TOA timeout delay for DS TWR extended frame (usec)'
        value: ((const uint16_t){0x10})

```

Regards Paul.

**Comment by enessuren** [comment]
Hi again,

i changed the file, result is same :( . im using windows 8.1 and i used "Apache MyNewt Quick Start" before i started. so this is my compiler i guess.

`
$ which arm-none-eabi-gcc                                         
 /c/Program Files (x86)/GNU Tools ARM Embedded/4.9 2015q2/bin/arm-n one-eabi-gcc
--

$ which arm-none-eabi-gdb                                          
/c/Program Files (x86)/GNU Tools ARM Embedded/4.9 2015q2/bin/arm-n one-eabi-gdb
--

**Comment by pkettle** [comment]
Hi Enes, 
We have not validated the stack on MinGW––this is on the TODO list. We are using OSX, Linux, and Ubuntu on WLS for our internal developments. Could I have you try the following? I have removed the {} from around the constants.

```
  TWR_DS_EXT_TX_HOLDOFF:
        description: 'tx holdoff delay for DS TWR extended frame (usec)'
        value: ((const uint32_t)0x0360)
      TWR_DS_EXT_RX_TIMEOUT:
        description: 'TOA timeout delay for DS TWR extended frame (usec)'
        value: ((const uint16_t)0x10)
```

Regards Paul.
